CREATE TABLE IF NOT EXISTS tasks (
  id VARCHAR(36) NOT NULL DEFAULT UUID(),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name VARCHAR(255) NOT NULL DEFAULT '',
  details TEXT NOT NULL DEFAULT '',
  completed TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);
