CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT AUTO_INCREMENT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  details VARCHAR(2000) NOT NULL DEFAULT '',
  completed TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

