CREATE TABLE IF NOT EXISTS notes (
  id BIGINT AUTO_INCREMENT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT '',
  body VARCHAR(2000) NOT NULL DEFAULT '',
  PRIMARY KEY (id)
);

