CREATE TABLE IF NOT EXISTS tasks (
  id BINARY(16) DEFAULT (UUID_TO_BIN(UUID(), 1)),
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT '',
  details VARCHAR(2000) NOT NULL DEFAULT '',
  completed TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
);

